{% set name = "plotly-resampler" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plotly-resampler-{{ version }}.tar.gz
  sha256: 8b747440afa6eb08e8503a3dde6bb3413be52a819a79a7a70308a089686e074a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.1,<3.11
  run:
    - dash >=2.2.0
    - flask-cors >=3.0.10
    - ipywidgets
    - jupyter-dash >=0.4.2
    - numpy >=1.21.0
    - lttbc
    - orjson >=3.6.8
    - pandas >=1.3.5
    - plotly >=5.6.0
    - python >=3.7.1,<3.11
    - trace-updater >=0.0.8

test:
  imports:
    - plotly_resampler
    - plotly_resampler.figure_resampler
    - plotly_resampler.aggregation
#  commands:
#    - pip check
#  requires:
#    - pip

about:
  home: https://github.com/predict-idlab/plotly-resampler
  doc_url: https://predict-idlab.github.io/plotly-resampler/
  summary: Visualizing large time series with plotly
  license: LicenseRef-plotly-resampler
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
