{% set name = "plotly-resampler" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plotly-resampler-{{ version }}.tar.gz
  sha256: fb1573d31f0955a19450c3e4152f7d0e5a83cdb0f50afd19f68ac9d1a34769bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - dash >=2.0.0
    - jupyter-dash >=0.4.0
    - lttbc >=0.2.0
    - orjson >=3.6.4
    - pandas >=1.3.5
    - plotly >=5.3.1
    - python >=3.7
    - trace-updater >=0.0.6

test:
  imports:
    - plotly_resampler
    - plotly_resampler.downsamplers
  commands:
    - pip list | grep -E '{{ name }}\s+{{ version }}'
  requires:
    - pip
    - m2-grep  # [win]

about:
  home: https://github.com/predict-idlab/plotly-resampler
  doc_url: https://predict-idlab.github.io/plotly-resampler/
  summary: Visualizing large time series with plotly
  license: LicenseRef-plotly-resampler
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
